# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0002_auto_20180526_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 18, 25, 20, 690898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 18, 25, 20, 688898, tzinfo=utc)),
        ),
    ]
