# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-27 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0004_auto_20180526_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 19, 33, 30, 45156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 19, 33, 30, 42656, tzinfo=utc)),
        ),
    ]
